-- Base schema scaffold for v1.2 lock implementation.

create table if not exists material_factors (
    material_id varchar(120) primary key,
    name varchar(200) not null,
    category varchar(20) not null,
    density_low double precision not null,
    density_typ double precision not null,
    density_high double precision not null,
    wet_multiplier_low double precision not null,
    wet_multiplier_high double precision not null,
    data_quality varchar(10) not null,
    source varchar(255),
    source_version_date date,
    updated_at timestamp default current_timestamp
);

create table if not exists unit_conversions (
    unit_id varchar(120) primary key,
    formula_type varchar(40) not null,
    material_required boolean not null,
    uncertainty_pct double precision not null,
    formula_expression varchar(4000) not null,
    updated_at timestamp default current_timestamp
);

create table if not exists dumpster_sizes (
    size_yd integer primary key,
    dimensions_approx varchar(80),
    included_tons_low double precision not null,
    included_tons_typ double precision not null,
    included_tons_high double precision not null,
    max_haul_tons_low double precision not null,
    max_haul_tons_typ double precision not null,
    max_haul_tons_high double precision not null,
    heavy_debris_max_fill_ratio double precision not null,
    clean_load_required_for_heavy boolean not null,
    updated_at timestamp default current_timestamp
);

create table if not exists pricing_assumptions (
    id bigint generated by default as identity primary key,
    size_yd integer not null,
    rental_fee_low double precision not null,
    rental_fee_typ double precision not null,
    rental_fee_high double precision not null,
    overage_fee_per_ton_low double precision not null,
    overage_fee_per_ton_typ double precision not null,
    overage_fee_per_ton_high double precision not null,
    haul_fee_low double precision not null,
    haul_fee_typ double precision not null,
    haul_fee_high double precision not null,
    junk_rate_basis varchar(120) not null,
    updated_at timestamp default current_timestamp
);

create table if not exists estimates (
    estimate_id varchar(64) primary key,
    created_at timestamp not null,
    expires_at timestamp not null,
    payload_json clob not null
);

create table if not exists tracking_events (
    id bigint generated by default as identity primary key,
    estimate_id varchar(64),
    event_name varchar(120) not null,
    event_payload clob,
    created_at timestamp not null
);
