-- Base schema scaffold for v1.2 lock implementation.

create table if not exists material_factors (
    material_id varchar(120) primary key,
    name varchar(200) not null,
    category varchar(20) not null,
    density_low double precision not null,
    density_typ double precision not null,
    density_high double precision not null,
    wet_multiplier_low double precision not null,
    wet_multiplier_high double precision not null,
    data_quality varchar(10) not null,
    source varchar(255),
    source_url varchar(1000),
    source_version_date date,
    updated_at timestamp default current_timestamp
);
alter table material_factors add column if not exists source_version_date date;
alter table material_factors add column if not exists source_url varchar(1000);

create table if not exists unit_conversions (
    unit_id varchar(120) primary key,
    formula_type varchar(40) not null,
    material_required boolean not null,
    uncertainty_pct double precision not null,
    formula_expression varchar(4000) not null,
    updated_at timestamp default current_timestamp
);

create table if not exists dumpster_sizes (
    size_yd integer primary key,
    dimensions_approx varchar(80),
    included_tons_low double precision not null,
    included_tons_typ double precision not null,
    included_tons_high double precision not null,
    max_haul_tons_low double precision not null,
    max_haul_tons_typ double precision not null,
    max_haul_tons_high double precision not null,
    heavy_debris_max_fill_ratio double precision not null,
    clean_load_required_for_heavy boolean not null,
    updated_at timestamp default current_timestamp
);

create table if not exists pricing_assumptions (
    id bigint generated by default as identity primary key,
    size_yd integer not null,
    rental_fee_low double precision not null,
    rental_fee_typ double precision not null,
    rental_fee_high double precision not null,
    overage_fee_per_ton_low double precision not null,
    overage_fee_per_ton_typ double precision not null,
    overage_fee_per_ton_high double precision not null,
    haul_fee_low double precision not null,
    haul_fee_typ double precision not null,
    haul_fee_high double precision not null,
    junk_rate_basis varchar(120) not null,
    updated_at timestamp default current_timestamp
);

create table if not exists junk_pricing_profiles (
    profile_id varchar(80) primary key,
    display_name varchar(200) not null,
    min_service_fee_low double precision not null,
    min_service_fee_typ double precision not null,
    min_service_fee_high double precision not null,
    per_cy_fee_low double precision not null,
    per_cy_fee_typ double precision not null,
    per_cy_fee_high double precision not null,
    minimum_billable_volume_cy double precision not null,
    truck_capacity_cy double precision not null,
    billing_increment_fraction double precision not null,
    dense_material_threshold_ton_per_cy double precision not null,
    dense_material_multiplier_low double precision not null,
    dense_material_multiplier_typ double precision not null,
    dense_material_multiplier_high double precision not null,
    data_quality varchar(10) not null,
    source varchar(255) not null,
    source_url varchar(1000),
    source_version_date date,
    notes varchar(2000),
    updated_at timestamp default current_timestamp
);

create table if not exists junk_pricing_profile_rules (
    rule_id varchar(80) primary key,
    market_tier varchar(40) not null,
    need_timing varchar(40) not null,
    profile_id varchar(80) not null,
    priority integer not null,
    source varchar(255) not null,
    source_url varchar(1000),
    source_version_date date,
    notes varchar(2000),
    updated_at timestamp default current_timestamp
);

create table if not exists junk_quote_benchmarks (
    benchmark_id varchar(80) primary key,
    market_tier varchar(40) not null,
    need_timing varchar(40) not null,
    scenario_tag varchar(80) not null,
    sample_count integer not null,
    volume_cy_low double precision not null,
    volume_cy_high double precision not null,
    quoted_total_low double precision not null,
    quoted_total_typ double precision not null,
    quoted_total_high double precision not null,
    min_fee_typ double precision not null,
    source varchar(255) not null,
    source_url varchar(1000),
    source_version_date date,
    notes varchar(2000),
    updated_at timestamp default current_timestamp
);
create index if not exists idx_junk_quote_benchmarks_tier_timing
    on junk_quote_benchmarks (market_tier, need_timing, sample_count);

create table if not exists market_tier_zip_overrides (
    rule_id varchar(80) primary key,
    zip_start varchar(5) not null,
    zip_end varchar(5) not null,
    market_tier varchar(40) not null,
    priority integer not null,
    source varchar(255) not null,
    source_url varchar(1000),
    source_version_date date,
    notes varchar(2000),
    updated_at timestamp default current_timestamp
);
create index if not exists idx_market_tier_zip_overrides_range
    on market_tier_zip_overrides (zip_start, zip_end, priority);

create table if not exists estimates (
    estimate_id varchar(64) primary key,
    created_at timestamp not null,
    expires_at timestamp not null,
    payload_json clob not null
);
create index if not exists idx_estimates_expires_at on estimates (expires_at);

create table if not exists quote_match_intakes (
    intake_id varchar(64) primary key,
    estimate_id varchar(64),
    status varchar(40) not null,
    zip_code varchar(5) not null,
    contact_method varchar(20) not null,
    contact_value varchar(255) not null,
    persona varchar(40),
    need_timing varchar(20),
    decision_mode varchar(40),
    recommended_route varchar(40),
    project_id varchar(120),
    material_ids varchar(1000),
    created_at timestamp not null,
    updated_at timestamp not null
);
create index if not exists idx_quote_match_intakes_created_at on quote_match_intakes (created_at);
create index if not exists idx_quote_match_intakes_status on quote_match_intakes (status);
create index if not exists idx_quote_match_intakes_zip on quote_match_intakes (zip_code);

create table if not exists tracking_events (
    id bigint generated by default as identity primary key,
    estimate_id varchar(64),
    event_name varchar(120) not null,
    event_payload clob,
    created_at timestamp not null
);
create index if not exists idx_tracking_events_created_at on tracking_events (created_at);
